// Automatically generated by astro-icon
// 2005968c4634d6fadfb6c522ff69b21a8cdb25c06b879bd1cb44c490d4613ef5

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrow"
		| "arrow-left"
		| "chevron-down"
		| "magnifying-glass"
		| "moon"
		| "search"
		| "sun"
		| "system";
}